POST http://localhost:8083/reservations
Content-Type: application/json

{
    "email": "cacciatoruben@icloud.com",
    "examId": 1
}

###

POST http://localhost:8083/reservations
Content-Type: application/json

{
    "email": "cacciatoruben@icloud.com",
    "examId": 3
}

###

POST http://localhost:8083/reservations
Content-Type: application/json

{
    "email": "paololima@gmail.com",
    "examId": 1
}

###

GET http://localhost:8083/reservations/cacciatoruben@icloud.com

###

GET http://localhost:8083/reservations/paololima@gmail.com

###

POST http://localhost:8083/reservations
Content-Type: application/json

{
    "email": "paololima@gmail.com",
    "examId": 3
}

###

GET http://localhost:8083/reservations?course_name=Sistemi cloud&date=2025-02-15T10:30:00

###

GET http://localhost:8083/reservations?course_name=Ingegneria dei sistemi distribuiti&date=2025-02-23T10:30:00

###

DELETE http://localhost:8083/reservations/1