name: CI/CD pipeline for Spring Boot microservices app

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: Build and push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push API gateway image
        run: |
          cd api-gateway
          mvn clean
          mvn package -DskipTests
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/api-gateway:v1.2 .
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/api-gateway:v1.2

      - name: Build and push course service image
        run: |
          cd course_ms
          mvn clean
          mvn package -DskipTests
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/course_ms:v1.2 .
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/course_ms:v1.2

      - name: Build and push exam service image
        run: |
          cd exam_ms
          mvn clean
          mvn package -DskipTests
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/exam_ms:v1.2 .
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/exam_ms:v1.2

      - name: Build and push reservation service image
        run: |
          cd reservation_ms
          mvn clean
          mvn package -DskipTests
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/reservation_ms:v1.2 .
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/reservation_ms:v1.2

      - name: Build and push result service image
        run: |
          cd result_ms
          mvn clean
          mvn package -DskipTests
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/result_ms:v1.2 .
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/result_ms:v1.2
      
      - name: Logout from Docker Hub
        run: docker logout

  deploy:
    name: Deploy
    needs: build-and-push
    runs-on: ubuntu-latest
    env:
      SSH_PK: ${{ secrets.SSH_PK }}
    steps:
      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: ./ansible/ansible_deploy_k8s/playbook.yml        
          key: ${{ secrets.SSH_PK }}
          inventory: |
            [masters]
            54.211.13.43 ansible_user=ubuntu